// Portuguese Pickleball Courts Data
const pickleballCourts = [
  {
    "Facility Name": "Lisboa Racket Centre",
    "Full Address": "R. Alferes Malheiro, 1700-025 Lisboa",
    "Latitude": "38.759719",
    "Longitude": "-9.153442",
    "Phone": "+351 21 846 0232",
    "Website": "http://lrc.pt/",
    "Email": "recepcao@lrc.pt",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"8am-12am\", \"Tuesday\": \"8am-12am\", \"Wednesday\": \"8am-12am\", \"Thursday\": \"8am-12am\", \"Friday\": \"8am-10:30pm\", \"Saturday\": \"9am-6pm\", \"Sunday\": \"9am-6pm\"}",
    "Additional Information": "Tennis, Padel, Squash, Swimming pool, Gym, Pro shop, Café with terrace",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Oeiras Padel Academy",
    "Full Address": "R. Joaquim Paço D' Arcos 1, 2740-286 Porto Salvo",
    "Latitude": "38.718818",
    "Longitude": "-9.310162",
    "Phone": "+351 964 139 083",
    "Website": "https://www.tiepadel.com/OeirasPadelAcademy",
    "Email": "geral@oeiraspadelacademy.pt",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\": \"7am-11am\", \"Tuesday\": \"7am-11am\", \"Wednesday\": \"7am-11am\", \"Thursday\": \"7am-11am\", \"Friday\": \"8am-10:30pm\", \"Saturday\": \"8am-11pm\", \"Sunday\": \"8am-11pm\"}",
    "Additional Information": "Padel (13 courts covered and 2 outdoor)",
    "District": "Lisboa"
  },
  {
    "Facility Name": "NovoPadel Club Setúbal",
    "Full Address": "R. Alexandre O'Neill 34, 2910-713 Setúbal",
    "Latitude": "38.525514",
    "Longitude": "-8.872877",
    "Phone": "+351 932 633 521",
    "Website": "https://www.instagram.com/novopadel/",
    "Email": "coelhonevespadel@gmail.com",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"9am-12am\", \"Tuesday\": \"9am-12am\", \"Wednesday\": \"9am-12am\", \"Thursday\": \"9am-12am\", \"Friday\": \"9am-12am\", \"Saturday\": \"9am-12am\", \"Sunday\": \"9am-12am\"}",
    "Additional Information": "Padel, Hotel restaurant and bar, Swimming pool, Gym",
    "District": "Setúbal"
  },
  {
    "Facility Name": "Turim Club d'Azeitão Hotel",
    "Full Address": "Urbanização do Bom Pastor, 2925-483 São Simão",
    "Latitude": "38.520499",
    "Longitude": "-9.006991",
    "Phone": "+351 300 528 059",
    "Website": "https://turim-hotels.com/en/new-pickeball-field/",
    "Email": "reservas@turimhoteis.com",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\": \"12am-12am\", \"Tuesday\": \"12am-12am\", \"Wednesday\": \"12am-12am\", \"Thursday\": \"12am-12am\", \"Friday\": \"12am-12am\", \"Saturday\": \"12am-12am\", \"Sunday\": \"12am-12am\"}",
    "Additional Information": "Hotel accommodation, Tennis court, Swimming pool, Restaurant, Bar",
    "District": "Setúbal"
  },
  {
    "Facility Name": "NUIKS Pickleball Club",
    "Full Address": "Largo Ilha 3, 4405 Vila Nova de Gaia, Portugal",
    "Latitude": "41.0963",
    "Longitude": "-8.6253",
    "Phone": "+351 923 353 928",
    "Website": "https://www.pickleheads.com/courts/pt/porto/vila-nova-de-gaia/nuiks-pickleball-club-polidesportivo-da-ilha",
    "Email": "",
    "Number of Courts": "4",
    "Operating Hours": "{\"Saturday\": \"9:30am-12:30am\"}",
    "Additional Information": "Public courts, shared nets, outdoor hard surface",
    "District": "Porto"
  },
  {
    "Facility Name": "Club Sportivo Nun'Alvares",
    "Full Address": "R. Particular de Monsanto 157, 4250-362 Porto",
    "Latitude": "41.171058",
    "Longitude": "-8.653457",
    "Phone": "+351 228 321 045",
    "Website": "https://www.csna.pt/",
    "Email": "secretaria.nun.alvares1@gmail.com",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\": \"8am-12am\", \"Tuesday\": \"8am-12am\", \"Wednesday\": \"8am-12am\", \"Thursday\": \"8am-12am\", \"Friday\": \"8am-12am\", \"Saturday\": \"8am-12am\", \"Sunday\": \"8am-8pm\"}",
    "Additional Information": "Tennis (6 courts), Squash, Capoeira, Futsal, CrossFit, Table Tennis",
    "District": "Porto"
  },
  {
    "Facility Name": "Complexo Desportivo Monte Aventino",
    "Full Address": "R. do Monte Aventino S/N, 4350-233 Porto",
    "Latitude": "41.161042",
    "Longitude": "-8.583921",
    "Phone": "+351 225 574 030",
    "Website": "https://www.tietennis.com/CDMonteAventin...",
    "Email": "monteaventino@fptenis.pt",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\": \"9am-11pm\", \"Tuesday\": \"9am-11pm\", \"Wednesday\": \"9am-11pm\", \"Thursday\": \"9am-11pm\", \"Friday\": \"9am-11pm\", \"Saturday\": \"9am-11pm\", \"Sunday\": \"9am-1pm\"}",
    "Additional Information": "Tennis (6 courts - 2 indoor, carpet/clay/grass), Pro shop, Bathrooms",
    "District": "Porto"
  },
  {
    "Facility Name": "Quinta Escondida da Avessadas",
    "Full Address": "Rua da Vessada 171, 4630-003 Avessadas",
    "Latitude": "41.157813",
    "Longitude": "-8.181958",
    "Phone": "+351 964 183 370",
    "Website": "https://www.facebook.com/QuintaEscondidaAvessadas",
    "Email": "quintaescondidaporto@gmail.com",
    "Number of Courts": "4",
    "Operating Hours": "{\"Monday\": \"Open 24 hours\", \"Tuesday\": \"Open 24 hours\", \"Wednesday\": \"Open 24 hours\", \"Thursday\": \"Open 24 hours\", \"Friday\": \"Open 24 hours\", \"Saturday\": \"Open 24 hours\", \"Sunday\": \"Open 24 hours\"}",
    "Additional Information": "Accommodation, Swimming pool",
    "District": "Porto"
  },
  {
    "Facility Name": "Clube de Ténis de Guimarães",
    "Full Address": "Urbanização da Feijoeira, 4800-029 Guimarães",
    "Latitude": "41.448532",
    "Longitude": "-8.303102",
    "Phone": "+351 253 512 579",
    "Website": "https://playtomic.com/clubs/clube-de-tenis-de-guimaraes",
    "Email": "clube.tenis.guimaraes@gmail.com",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\": \"9am-12am\", \"Tuesday\": \"9am-12am\", \"Wednesday\": \"9am-12am\", \"Thursday\": \"9am-12am\", \"Friday\": \"9am-12am\", \"Saturday\": \"9am-8pm\", \"Sunday\": \"9am-8pm\"}",
    "Additional Information": "Tennis (7 courts - 4 outdoor fast court, 3 indoor clay), Padel (3 courts), Restaurant with terrace, Social lounge, Physiotherapy clinic",
    "District": "Braga"
  },
  {
    "Facility Name": "FUT7 Braga (Desportos e Lazer)",
    "Full Address": "Rua de Entrecampos 91, Palmeira, 4700-753 Braga",
    "Latitude": "41.587823",
    "Longitude": "-8.441029",
    "Phone": "+351 253 323 669",
    "Website": "http://fut7.pt/",
    "Email": "info@fut7.pt",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"8am-12am\", \"Tuesday\": \"8am-12am\", \"Wednesday\": \"8am-12am\", \"Thursday\": \"8am-12am\", \"Friday\": \"8am-12am\", \"Saturday\": \"8am-9pm\", \"Sunday\": \"8am-2pm\"}",
    "Additional Information": "Football (3 synthetic grass courts), Padel (4 covered courts), Tennis (1 indoor court), Beach tennis/Futevolei, Gym, Restaurant/Bar, School activities",
    "District": "Braga"
  },
  {
    "Facility Name": "Viana do Castelo Pickleball (Pavilhão N. Veríssimo)",
    "Full Address": "Largo Prof.ª Maria Claudina Branco, 4900-076 Viana do Castelo",
    "Latitude": "41.694601",
    "Longitude": "-8.830164",
    "Phone": "+351 258 823 464",
    "Website": "",
    "Email": "",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"5:30pm-8pm\", \"Tuesday\": \"Closed\", \"Wednesday\": \"5:30pm-8pm\", \"Thursday\": \"Closed\", \"Friday\": \"Closed\", \"Saturday\": \"Closed\", \"Sunday\": \"Closed\"}",
    "Additional Information": "Municipal program, free lessons, equipment provided",
    "District": "Viana do Castelo"
  },
  {
    "Facility Name": "Rocha Brava Racquet Club",
    "Full Address": "Urb. Rocha Brava, Praia do Carvoeiro, 8401-908 Carvoeiro (Lagoa)",
    "Latitude": "37.093551",
    "Longitude": "-8.452814",
    "Phone": "+351 911 740 098",
    "Website": "https://rochabravarc.com/",
    "Email": "rochabrava@nordapadel.com",
    "Number of Courts": "8",
    "Operating Hours": "{\"Monday\": \"8:30am-6:00pm\", \"Tuesday\": \"8:30am-6:00pm\", \"Wednesday\": \"8:30am-6:00pm\", \"Thursday\": \"8:30am-6:00pm\", \"Friday\": \"8:30am-6:00pm\", \"Saturday\": \"8:30am-4:00pm\", \"Sunday\": \"8:30am-4:00pm\"}",
    "Additional Information": "Tennis, Social tennis meetup (Wed/Fri/Sun 10am-12pm), Tennis academy, Kids tennis academy, Tennis holidays packages",
    "District": "Faro"
  },
  {
    "Facility Name": "Lagos Tenis Center & Pickleball",
    "Full Address": "Rua Aldeia da Torraltinha 3B, 8600-611 Lagos",
    "Latitude": "37.098418",
    "Longitude": "-8.681123",
    "Phone": "+351 916 175 231",
    "Website": "https://www.facebook.com/",
    "Email": "lagosteniscenter@gmail.com",
    "Number of Courts": "8",
    "Operating Hours": "{\"Monday\": \"8:30am-6:00pm\", \"Tuesday\": \"8:30am-6:00pm\", \"Wednesday\": \"8:30am-6:00pm\", \"Thursday\": \"8:30am-6:00pm\", \"Friday\": \"8:30am-6:00pm\", \"Saturday\": \"8:30am-4:00pm\", \"Sunday\": \"8:30am-4:00pm\"}",
    "Additional Information": "Permanent lines, €5/session, non-marking shoes required",
    "District": "Faro"
  },
  {
    "Facility Name": "Jim Stewart Tennis Academy (Quinta do Lago)",
    "Full Address": "Urbanização Vilar do Golf, Quinta do Lago, 8135-024 Almancil",
    "Latitude": "37.049444",
    "Longitude": "-8.026389",
    "Phone": "+351 289 398 848",
    "Website": "http://www.spanglefish.com/algarveportugal/",
    "Email": "club@playtennisalgarve.com",
    "Number of Courts": "1",
    "Operating Hours": "",
    "Additional Information": "Tennis academy (multiple courts including Euroclay artificial clay), Tennis coaching packages, Club shop, Bar/restaurant",
    "District": "Faro"
  },
  {
    "Facility Name": "Vilamoura Tennis & Padel Academy",
    "Full Address": "Av. Eng. João Meireles, Vilamoura, 8125-406 Quarteira",
    "Latitude": "37.081827",
    "Longitude": "-8.118931",
    "Phone": "+351 912 259 376",
    "Website": "https://www.tietennis.com/vilamoura",
    "Email": "vta@premier-sports.org",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"9am-9pm\", \"Tuesday\": \"9am-9pm\", \"Wednesday\": \"9am-9pm\", \"Thursday\": \"9am-9pm\", \"Friday\": \"9am-9pm\", \"Saturday\": \"9am-9pm\", \"Sunday\": \"9am-9pm\"}",
    "Additional Information": "Tennis (9 courts - 4 floodlit), Padel (5 courts), Mini tennis (4 courts), Mini football, Pro shop, Restaurant/Pizzaria, Tennis school, Padel school",
    "District": "Faro"
  },
  {
    "Facility Name": "Clube Ténis VRSA",
    "Full Address": "Av. Ministro Duarte Pacheco, 8900-211 Vila Real de Santo António",
    "Latitude": "37.194451",
    "Longitude": "-7.416853",
    "Phone": "+351 963 802 171",
    "Website": "https://tenisvrsa.com/",
    "Email": "geral@tenisvrsa.com",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\": \"9am-12pm, 4pm-8pm\", \"Tuesday\": \"9am-12pm, 4pm-8pm\", \"Wednesday\": \"9am-12pm, 4pm-8pm\", \"Thursday\": \"9am-12pm, 4pm-8pm\", \"Friday\": \"9am-12pm, 4pm-8pm\", \"Saturday\": \"9am-12pm, 4pm-8pm\", \"Sunday\": \"Closed\"}",
    "Additional Information": "Tennis (5 clay courts, 4 hard courts), Padel (2 courts), Pro shop, Café, Racket stringing service, Mini-tennis programs for ages 4+, Netball",
    "District": "Faro"
  }
];
