// Portuguese Pickleball Courts Data
const pickleballCourts = [
  {
    "Facility Name": "Nuiks - Polidesportivo da Ilha",
    "Full Address": "Rua da Gândara, Vilar do Paraíso, Vila Nova de Gaia",
    "Latitude": "41.116",
    "Longitude": "-8.633",
    "Phone": "+351 92 335 3928",
    "Website": "https://www.tiepadel.com/Nuiks",
    "Email": "geral@nuiks.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-12am\",\"Tuesday\":\"9am-12am\",\"Wednesday\":\"9am-12am\",\"Thursday\":\"9am-12am\",\"Friday\":\"9am-12am\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Equipment rental, Lessons, Social sessions, Sports complex",
    "District": "Porto"
  },
  {
    "Facility Name": "BPickleball",
    "Full Address": "R. Padre António José Barreiros, Braga",
    "Latitude": "41.545",
    "Longitude": "-8.426",
    "Phone": "+351 938 437 688",
    "Website": "https://www.facebook.com/bpickleball",
    "Email": "bpickleball@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-12am\",\"Tuesday\":\"7am-12am\",\"Wednesday\":\"7am-12am\",\"Thursday\":\"7am-12am\",\"Friday\":\"7am-12am\",\"Saturday\":\"8am-10pm\",\"Sunday\":\"8am-9pm\"}",
    "Additional Information": "Pro shop, Lessons, Tournaments",
    "District": "Braga"
  },
  {
    "Facility Name": "Lemonfit Maia",
    "Full Address": "R. Dr. Gonçalo de Araújo 298, Maia",
    "Latitude": "41.228",
    "Longitude": "-8.621",
    "Phone": "+ 351 223 243 800",
    "Website": "https://www.lemonfit.pt/lemonfit-padel-maia",
    "Email": "geral.maia@lemonfit.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"6:30am-12am\",\"Tuesday\":\"6:30am-12am\",\"Wednesday\":\"6:30am-12am\",\"Thursday\":\"6:30am-12am\",\"Friday\":\"6:30am-12am\",\"Saturday\":\"8am-8pm\",\"Sunday\":\"8am-2pm\"}",
    "Additional Information": "Gym, Padel, Fitness classes, Sauna",
    "District": "Porto"
  },
  {
    "Facility Name": "The Lob - Padel Academy",
    "Full Address": "R. Picoutos, 4465-231 São Mamede de Infesta, Porto",
    "Latitude": "41.189",
    "Longitude": "-8.605",
    "Phone": "+351 912 795 586",
    "Website": "https://www.aircourts.com/index.php/site/view_club/656",
    "Email": "welobpadel@gmail.com",
    "Number of Courts": "4",
    "Operating Hours": "{\"Monday\":\"9am-11:30pm\",\"Tuesday\":\"9am-11:30pm\",\"Wednesday\":\"9am-11:30pm\",\"Thursday\":\"9am-11:30pm\",\"Friday\":\"9am-12am\",\"Saturday\":\"9am-11:30pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Padel, Indoor courts, Bar, Lounge",
    "District": "Porto"
  },
  {
    "Facility Name": "Clube de Ténis de Guimarães",
    "Full Address": "Urbanização da Feijoeira, Guimarães",
    "Latitude": "41.442",
    "Longitude": "-8.291",
    "Phone": "+351 253 512 579",
    "Website": "http://www.clubetenisguimaraes.com/",
    "Email": "clube.tenis.guimaraes@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-12am\",\"Tuesday\":\"9am-12am\",\"Wednesday\":\"9am-12am\",\"Thursday\":\"9am-12am\",\"Friday\":\"9am-12am\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Tennis, Padel, Clay courts, Restaurant",
    "District": "Braga"
  },
  {
    "Facility Name": "Viana Pickleball",
    "Full Address": "Pav. Municipal David Meira Freitas, Caminho de Paranhos 222, Afife, Viana do Castelo",
    "Latitude": "41.693",
    "Longitude": "-8.828",
    "Phone": "",
    "Website": "https://www.facebook.com/groups/vianapickleball",
    "Email": "info@padelviana.pt",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\":\"9am-12am\",\"Tuesday\":\"9am-12am\",\"Wednesday\":\"9am-12am\",\"Thursday\":\"9am-12am\",\"Friday\":\"9am-12am\",\"Saturday\":\"9am-12am\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Padel, Academy, Bar",
    "District": "Viana do Castelo"
  },
  {
    "Facility Name": "Pickleball Academy Braga",
    "Full Address": "R. da Eira 28, Braga",
    "Latitude": "41.55",
    "Longitude": "-8.4",
    "Phone": "+351 914 075 678",
    "Website": "https://www.facebook.com/profile.php?id=61572530131416",
    "Email": "geral@ufnogueiro-tenoes.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"Closed\",\"Tuesday\":\"Closed\",\"Wednesday\":\"Closed\",\"Thursday\":\"2pm-7pm\",\"Friday\":\"9am-12pm\",\"Saturday\":\"2pm-7pm\",\"Sunday\":\"9am-12pm\"}",
    "Additional Information": "Community center, Lessons",
    "District": "Braga"
  },
  {
    "Facility Name": "Pickleball Racket Club",
    "Full Address": "R. Restauradores do Brás-de-Oleiros Maia",
    "Latitude": "41.233",
    "Longitude": "-8.624",
    "Phone": "+351 916 400 368",
    "Website": "https://www.facebook.com/p/Pickleball-RC-61554012287017/",
    "Email": "Not specified",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-11pm\",\"Tuesday\":\"9am-11pm\",\"Wednesday\":\"9am-11pm\",\"Thursday\":\"9am-11pm\",\"Friday\":\"9am-11pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Racket sports",
    "District": "Porto"
  },
  {
    "Facility Name": "Quinta Escondida da Avessadas",
    "Full Address": "Rua da Vessada 171, 4630-003 Avessadas",
    "Latitude": "41.183",
    "Longitude": "-8.15",
    "Phone": "+351 934 415 459",
    "Website": "https://www.facebook.com/lmpillatsch/?locale=pt_PT",
    "Email": "quintaescondidaporto@gmail.com",
    "Number of Courts": "4",
    "Operating Hours": "{\"Monday\":\"9am-8pm\",\"Tuesday\":\"9am-8pm\",\"Wednesday\":\"9am-8pm\",\"Thursday\":\"9am-8pm\",\"Friday\":\"9am-8pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Accommodation, Nature, Private courts",
    "District": "Porto"
  },
  {
    "Facility Name": "Open Village Sports Hotel & Spa",
    "Full Address": "Tv. da Ribeira 629, 4810-235 Guimarães",
    "Latitude": "41.442",
    "Longitude": "-8.25",
    "Phone": "+351 253 540 630",
    "Website": "https://www.ovs.pt/",
    "Email": "geral@ovs.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-11pm\",\"Tuesday\":\"7am-11pm\",\"Wednesday\":\"7am-11pm\",\"Thursday\":\"7am-11pm\",\"Friday\":\"7am-11pm\",\"Saturday\":\"8am-10pm\",\"Sunday\":\"8am-8pm\"}",
    "Additional Information": "Hotel, Spa, Gym, Tennis, Football",
    "District": "Braga"
  },
  {
    "Facility Name": "Associação Cultural E Desportiva \"Os Beirões\" De Maçainhas",
    "Full Address": "Complexo Desportivo Os Beirões , Maçainhas de Baixo",
    "Latitude": "40.583",
    "Longitude": "-7.333",
    "Phone": "",
    "Website": "https://www.facebook.com/p/Associa%C3%A7%C3%A3o-Cultural-E-Desportiva-Os-Beir%C3%B5es-De-Ma%C3%A7ainhas-100080303273938/?locale=pt_PT",
    "Email": "pickleballbeiroes@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-9pm\",\"Tuesday\":\"9am-9pm\",\"Wednesday\":\"9am-9pm\",\"Thursday\":\"9am-9pm\",\"Friday\":\"9am-9pm\",\"Saturday\":\"9am-9pm\",\"Sunday\":\"9am-9pm\"}",
    "Additional Information": "Community sports, Events",
    "District": "Guarda"
  },
  {
    "Facility Name": "NAVE | Padel x Pickleball",
    "Full Address": "Rua do Açúcar 19, 1950-242 Lisboa",
    "Latitude": "38.741",
    "Longitude": "-9.102",
    "Phone": "+351 910 574 176",
    "Website": "https://linktr.ee/navepadel",
    "Email": "geral@navepadel.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8am-12am\",\"Tuesday\":\"8am-12am\",\"Wednesday\":\"8am-12am\",\"Thursday\":\"8am-12am\",\"Friday\":\"8am-12am\",\"Saturday\":\"9am-9pm\",\"Sunday\":\"9am-9pm\"}",
    "Additional Information": "Padel, Indoor courts, Bar",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Associação ARDC Vauense (Silver Coast Pickleball Club)",
    "Full Address": "Rua do Juncal nº2 , Vau, Óbidos",
    "Latitude": "39.377",
    "Longitude": "-9.219",
    "Phone": "+351 961 655 279",
    "Website": "https://www.facebook.com/ARDCpickleballvau",
    "Email": "silvercoastpickleball@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-10pm\",\"Tuesday\":\"9am-10pm\",\"Wednesday\":\"9am-10pm\",\"Thursday\":\"9am-10pm\",\"Friday\":\"9am-10pm\",\"Saturday\":\"9am-10pm\",\"Sunday\":\"9am-10pm\"}",
    "Additional Information": "Community club",
    "District": "Leiria"
  },
  {
    "Facility Name": "Oeiras Padel Academy",
    "Full Address": "Rua Joaquim Paço de Arcos, nº1, Porto Salvo",
    "Latitude": "38.706",
    "Longitude": "-9.302",
    "Phone": "+351 964 139 083",
    "Website": "https://www.tiepadel.com/OeirasPadelAcademy",
    "Email": "geral@oeiraspadelacademy.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-11pm\",\"Tuesday\":\"7am-11pm\",\"Wednesday\":\"7am-11pm\",\"Thursday\":\"7am-11pm\",\"Friday\":\"8am-10:30pm\",\"Saturday\":\"8am-11pm\",\"Sunday\":\"8am-11pm\"}",
    "Additional Information": "Padel, Academy, Tournaments",
    "District": "Lisboa"
  },
  {
    "Facility Name": "NovoPadel Club Setúbal",
    "Full Address": "Rua Alexandre O'Neill 34, 2910-713 Setúbal",
    "Latitude": "38.524",
    "Longitude": "-8.893",
    "Phone": "+351 932 633 521",
    "Website": "https://www.pickleheads.com/courts/pt/setubal/setubal/novopadel-club-setubal",
    "Email": "coelhonevespadel@gmail.com",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\":\"9am-12am\",\"Tuesday\":\"9am-12am\",\"Wednesday\":\"9am-12am\",\"Thursday\":\"9am-12am\",\"Friday\":\"9am-12am\",\"Saturday\":\"9am-12am\",\"Sunday\":\"9am-12am\"}",
    "Additional Information": "Padel, Gym, Bar, Shop",
    "District": "Setúbal"
  },
  {
    "Facility Name": "CoolGym CoolPadel Ericeira",
    "Full Address": "Rua Casal Cordeiro, 2655-450 Ericeira",
    "Latitude": "38.964",
    "Longitude": "-9.416",
    "Phone": "+351 964 718 655",
    "Website": "https://www.tiepadel.com/CoolPadelEriceira",
    "Email": "coolgym.ericeira@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-10pm\",\"Tuesday\":\"7am-10pm\",\"Wednesday\":\"7am-10pm\",\"Thursday\":\"7am-10pm\",\"Friday\":\"7am-10pm\",\"Saturday\":\"8am-8pm\",\"Sunday\":\"8am-7pm\"}",
    "Additional Information": "Gym, Padel, Fitness classes",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Clube de Ténis de Santarém",
    "Full Address": "Largo Comendador Paulino da Cunha e Silva, Santarém",
    "Latitude": "39.233",
    "Longitude": "-8.683",
    "Phone": "+351 243 306 289",
    "Website": "http://www.ctsantarem.com/",
    "Email": "ctsantarem@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-10pm\",\"Tuesday\":\"9am-10pm\",\"Wednesday\":\"9am-10pm\",\"Thursday\":\"9am-10pm\",\"Friday\":\"9am-10pm\",\"Saturday\":\"10am-6pm\",\"Sunday\":\"10am-1pm\"}",
    "Additional Information": "Tennis, School, Events",
    "District": "Santarém"
  },
  {
    "Facility Name": "Clube Pickleball Leiria",
    "Full Address": "Urbanização Belo Horizonte, 2400-829 Leiria",
    "Latitude": "39.743",
    "Longitude": "-8.807",
    "Phone": "+351 936 304 536",
    "Website": "https://www.clubepickleball.pt/",
    "Email": "clubepickleballleiria@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-9pm\",\"Tuesday\":\"9am-9pm\",\"Wednesday\":\"9am-9pm\",\"Thursday\":\"9am-9pm\",\"Friday\":\"9am-9pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"Closed\"}",
    "Additional Information": "Tournaments, Lessons",
    "District": "Leiria"
  },
  {
    "Facility Name": "Clube Pickleball do Oeste",
    "Full Address": "Rua Casal dos Barreiros 2 ARDC Arneirense, Caldas da Rainha",
    "Latitude": "39.407",
    "Longitude": "-9.134",
    "Phone": "+351 918 736 200",
    "Website": "https://www.facebook.com/pickleballcaldas/",
    "Email": "clubepickleballoeste@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9:30am-6pm\",\"Tuesday\":\"9:30am-6pm\",\"Wednesday\":\"9:30am-6pm\",\"Thursday\":\"9:30am-6pm\",\"Friday\":\"9:30am-6pm\",\"Saturday\":\"Closed\",\"Sunday\":\"Closed\"}",
    "Additional Information": "Indoor courts, Social play",
    "District": "Leiria"
  },
  {
    "Facility Name": "Pickleball Torres Vedras",
    "Full Address": "Dolce CampoReal, Torres Vedras",
    "Latitude": "39.091",
    "Longitude": "-9.26",
    "Phone": "+351 910 095 170",
    "Website": "https://www.facebook.com/groups/26894900743488535/",
    "Email": "PORTUGALPICKLEBALLZONE@GMAIL.COM",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"Closed\",\"Tuesday\":\"Closed\",\"Wednesday\":\"Closed\",\"Thursday\":\"Closed\",\"Friday\":\"3pm-8pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Events, Tournaments",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Turim Club d'Azeitão Hotel",
    "Full Address": "Urbanização do Bom Pastor, São Simão, Azeitão",
    "Latitude": "38.517",
    "Longitude": "-9.015",
    "Phone": "+351 212 198 590",
    "Website": "https://turim-hotels.com/hotel-club-dazeitao-pt/?partner=8048utm_source=google&utm_medium=organic&utm_campaign=MyBusiness&utm",
    "Email": "hotelclubazeitao@turimhoteis.com",
    "Number of Courts": "1",
    "Operating Hours": "{\"Monday\":\"8am-8pm\",\"Tuesday\":\"8am-8pm\",\"Wednesday\":\"8am-8pm\",\"Thursday\":\"8am-8pm\",\"Friday\":\"8am-8pm\",\"Saturday\":\"8am-8pm\",\"Sunday\":\"8am-8pm\"}",
    "Additional Information": "Hotel, Tennis, Pool, Restaurant",
    "District": "Setúbal"
  },
  {
    "Facility Name": "Pickleball Clube da Pampilhosa",
    "Full Address": "Urbanização Alto de Santo António, 3050-456 Pampilhosa do Botão",
    "Latitude": "40.383",
    "Longitude": "-8.416",
    "Phone": "+351 911 841 177",
    "Website": "https://www.tiktok.com/@pickleball.clube",
    "Email": "pickleball.pampilhosa@gmail.com",
    "Number of Courts": "2",
    "Operating Hours": "{\"Monday\":\"6:30pm-9pm\",\"Tuesday\":\"6:30pm-9pm\",\"Wednesday\":\"6:30pm-9pm\",\"Thursday\":\"6:30pm-9pm\",\"Friday\":\"6:30pm-9pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"9am-6pm\"}",
    "Additional Information": "Free equipment rental, Outdoor courts",
    "District": "Aveiro"
  },
  {
    "Facility Name": "Assoc. de Moradores do Bº do Junqueiro (Clube Pickleball Lisboa)",
    "Full Address": "R. Benguela, 2775-330 Parede",
    "Latitude": "38.692",
    "Longitude": "-9.355",
    "Phone": "+351 911 841 177",
    "Website": "https://www.facebook.com/groups/pickleballlisboa",
    "Email": "pickleballlisboa@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-9pm\",\"Tuesday\":\"9am-9pm\",\"Wednesday\":\"9am-9pm\",\"Thursday\":\"9am-9pm\",\"Friday\":\"9am-9pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"9am-6pm\"}",
    "Additional Information": "Community association, Events",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Aroeira Tennis e Padel",
    "Full Address": "Tennis & Padel, 2820-567 Aroeira",
    "Latitude": "38.603",
    "Longitude": "-9.156",
    "Phone": "+ 351 927 239 978",
    "Website": "https://www.matchpointeam.com/aroeiratennispadelnew",
    "Email": "matchpointeam@outlook.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8am-10:30pm\",\"Tuesday\":\"8am-10:30pm\",\"Wednesday\":\"8am-10:30pm\",\"Thursday\":\"8am-10:30pm\",\"Friday\":\"8am-10:30pm\",\"Saturday\":\"8am-10:30pm\",\"Sunday\":\"8am-10:30pm\"}",
    "Additional Information": "Tennis, Padel, Shop",
    "District": "Setúbal"
  },
  {
    "Facility Name": "Lemonfit Olaias",
    "Full Address": "R. Robalo Gouveia 2, 1900-392 Lisboa",
    "Latitude": "38.739",
    "Longitude": "-9.121",
    "Phone": "+ 351 218 081 934",
    "Website": "https://www.lemonfit.pt/olaias",
    "Email": "geral.olaias@lemonfit.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-12am\",\"Tuesday\":\"7am-12am\",\"Wednesday\":\"7am-12am\",\"Thursday\":\"7am-12am\",\"Friday\":\"7am-12am\",\"Saturday\":\"8am-11pm\",\"Sunday\":\"9am-11pm\"}",
    "Additional Information": "Gym, Pool, Spa, Padel",
    "District": "Lisboa"
  },
  {
    "Facility Name": "Clube de Praticantes de Pickleball de Pinheiro de Ázere",
    "Full Address": "Rua S. Sebastião, Pinheiro de Ázere, Santa Comba Dão",
    "Latitude": "40.37",
    "Longitude": "-8.16",
    "Phone": "+ 351 963 381 472",
    "Website": "https://www.pickleheads.com/courts/pt/viana-do-castelo/moreira-do-lima/campo-poliesportivo-de-pinheiro-de-azere",
    "Email": "juntapinheiro@hotmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-5pm\",\"Tuesday\":\"9am-5pm\",\"Wednesday\":\"9am-5pm\",\"Thursday\":\"9am-5pm\",\"Friday\":\"9am-5pm\",\"Saturday\":\"Closed\",\"Sunday\":\"Closed\"}",
    "Additional Information": "Community courts",
    "District": "Viseu"
  },
  {
    "Facility Name": "Sport Club de Lavos",
    "Full Address": "Rua do, R. Sport Clube de Lavos 19, Figueira da Foz",
    "Latitude": "40.104",
    "Longitude": "-8.864",
    "Phone": "+351 932 518 865",
    "Website": "https://www.facebook.com/sportclubdelavos/",
    "Email": "LAVOSBASEBOL@GMAIL.COM",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-10pm\",\"Tuesday\":\"9am-10pm\",\"Wednesday\":\"9am-10pm\",\"Thursday\":\"9am-10pm\",\"Friday\":\"9am-10pm\",\"Saturday\":\"9am-10pm\",\"Sunday\":\"9am-10pm\"}",
    "Additional Information": "Baseball, Multisport",
    "District": "Coimbra"
  },
  {
    "Facility Name": "ARCLAB - Associação Recreativa e Cultural de Labrengos",
    "Full Address": "Praça Marquês de Marialva, Covões, Cantanhede",
    "Latitude": "40.383",
    "Longitude": "-8.6",
    "Phone": "+351 961 937 895",
    "Website": "https://www.cm-cantanhede.pt/mcsite/Entidade/3060/arclab--associacao-recreativa-e-cultural-de-labrengos",
    "Email": "arclabrengos@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-8pm\",\"Tuesday\":\"9am-8pm\",\"Wednesday\":\"9am-8pm\",\"Thursday\":\"9am-8pm\",\"Friday\":\"9am-8pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Cultural events, Recreation",
    "District": "Coimbra"
  },
  {
    "Facility Name": "Pickleball Clube Alvor",
    "Full Address": "Praceta Júlio Amaro, 8500-001 Alvor",
    "Latitude": "37.13",
    "Longitude": "-8.59",
    "Phone": "+351 939 505 811",
    "Website": "https://www.facebook.com/profile.php?id=61560820150364",
    "Email": "pickleballclubealvor@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-9pm\",\"Tuesday\":\"9am-9pm\",\"Wednesday\":\"9am-9pm\",\"Thursday\":\"9am-9pm\",\"Friday\":\"9am-9pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"9am-6pm\"}",
    "Additional Information": "Bowls, Social club",
    "District": "Faro"
  },
  {
    "Facility Name": "Complexo Desportivo de Alvor",
    "Full Address": "Sitio da Restinga, 8500-021 Alvor",
    "Latitude": "37.13",
    "Longitude": "-8.59",
    "Phone": "+351 962 289 983",
    "Website": "https://playtimescheduler.com/region/alvor-algarve",
    "Email": "Not specified",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"10am-12pm\",\"Tuesday\":\"By appointment\",\"Wednesday\":\"By appointment\",\"Thursday\":\"10am-12pm\",\"Friday\":\"By appointment\",\"Saturday\":\"By appointment\",\"Sunday\":\"By appointment\"}",
    "Additional Information": "Sports complex, Pool",
    "District": "Faro"
  },
  {
    "Facility Name": "Burgau Sports Centre",
    "Full Address": "Budens, 8650-040 Vila do Bispo",
    "Latitude": "37.072",
    "Longitude": "-8.775",
    "Phone": "+351 965 448 247",
    "Website": "https://www.burgausportscentre.com/",
    "Email": "burgauholidays@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-6pm\",\"Tuesday\":\"9am-6pm\",\"Wednesday\":\"9am-6pm\",\"Thursday\":\"9am-6pm\",\"Friday\":\"9am-6pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"9am-6pm\"}",
    "Additional Information": "Tennis, Pool, Squash, Apartments",
    "District": "Faro"
  },
  {
    "Facility Name": "B&B Jacob Albufeira Portugal",
    "Full Address": "Rua Alto de Patroves 809, Albufeira",
    "Latitude": "37.09",
    "Longitude": "-8.24",
    "Phone": "+351 917 225 220",
    "Website": "https://www.jacobinportugal.com/",
    "Email": "info@jacobinportugal.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-8pm\",\"Tuesday\":\"9am-8pm\",\"Wednesday\":\"9am-8pm\",\"Thursday\":\"9am-8pm\",\"Friday\":\"9am-8pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Accommodation, Private court",
    "District": "Faro"
  },
  {
    "Facility Name": "Rocha Brava Racquet Club",
    "Full Address": "Urb. Rocha Brava, Alfanzina, Praia do Carvoeiro",
    "Latitude": "37.093",
    "Longitude": "-8.47",
    "Phone": "+351 911 740 098",
    "Website": "https://rochabravarc.com/",
    "Email": "rochabrava@nordapadel.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8:30am-6pm\",\"Tuesday\":\"8:30am-6pm\",\"Wednesday\":\"8:30am-6pm\",\"Thursday\":\"8:30am-6pm\",\"Friday\":\"8:30am-6pm\",\"Saturday\":\"8:30am-4pm\",\"Sunday\":\"8:30am-4pm\"}",
    "Additional Information": "Tennis, Padel, Resort, Pool",
    "District": "Faro"
  },
  {
    "Facility Name": "Carvoeiro Clube de Ténis",
    "Full Address": "Rua Vale da Lapa, 8400-556 Lagoa",
    "Latitude": "37.098",
    "Longitude": "-8.467",
    "Phone": "+351 282 358 236",
    "Website": "https://www.carvoeiroclubegroup.com/en/sports-leisure-api/item/5179-carvoeiro-clube-de-tenis-e-padel",
    "Email": "geral@tenniscarvoeiro.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8am-8pm\",\"Tuesday\":\"8am-8pm\",\"Wednesday\":\"8am-8pm\",\"Thursday\":\"8am-8pm\",\"Friday\":\"8am-8pm\",\"Saturday\":\"8am-8pm\",\"Sunday\":\"8am-8pm\"}",
    "Additional Information": "Tennis, Gym, Wellness",
    "District": "Faro"
  },
  {
    "Facility Name": "Pestana Gramacho Residences",
    "Full Address": "Apartado 1011 8401-908 Lagoa, Algarve",
    "Latitude": "37.13",
    "Longitude": "-8.45",
    "Phone": "+351 282 340 900",
    "Website": "https://www.pestana.com/en/hotel/pestana-gramacho-residences?utm_campaign=pestana-gramacho-residences-partoo&utm_medium=organicsearch",
    "Email": "fo.carvoeiro@pestana.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"7am-10pm\",\"Tuesday\":\"7am-10pm\",\"Wednesday\":\"7am-10pm\",\"Thursday\":\"7am-10pm\",\"Friday\":\"7am-10pm\",\"Saturday\":\"7am-10pm\",\"Sunday\":\"7am-10pm\"}",
    "Additional Information": "Golf, Spa, Restaurant, Hotel",
    "District": "Faro"
  },
  {
    "Facility Name": "Lagoa Pickleball",
    "Full Address": "Polidesportivo de Sesmarias, Lagoa",
    "Latitude": "37.12",
    "Longitude": "-8.48",
    "Phone": "",
    "Website": "",
    "Email": "Not specified",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"Available\",\"Tuesday\":\"Available\",\"Wednesday\":\"Available\",\"Thursday\":\"Available\",\"Friday\":\"Available\",\"Saturday\":\"Available\",\"Sunday\":\"Available\"}",
    "Additional Information": "Public courts",
    "District": "Faro"
  },
  {
    "Facility Name": "Browns Sports Resort",
    "Full Address": "Caminho dos golfes, 8125-426 Quarteira",
    "Latitude": "37.105",
    "Longitude": "-8.115",
    "Phone": "+351 289 322 740",
    "Website": "https://www.brownssportsresort.com/en/",
    "Email": "info@browns-club.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8am-8pm\",\"Tuesday\":\"8am-8pm\",\"Wednesday\":\"8am-8pm\",\"Thursday\":\"8am-8pm\",\"Friday\":\"8am-8pm\",\"Saturday\":\"8am-8pm\",\"Sunday\":\"8am-8pm\"}",
    "Additional Information": "Resort, High performance center, Pool, Football",
    "District": "Faro"
  },
  {
    "Facility Name": "Quinta do Caracol",
    "Full Address": "Rua de S. Pedro, 11, 8800-405 Tavira",
    "Latitude": "37.125",
    "Longitude": "-7.65",
    "Phone": "+351 281 322 247",
    "Website": "",
    "Email": "info@quintadocaracol.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-6pm\",\"Tuesday\":\"9am-6pm\",\"Wednesday\":\"9am-6pm\",\"Thursday\":\"9am-6pm\",\"Friday\":\"9am-6pm\",\"Saturday\":\"9am-6pm\",\"Sunday\":\"9am-6pm\"}",
    "Additional Information": "Accommodation, Private court",
    "District": "Faro"
  },
  {
    "Facility Name": "Vilamoura Tennis & Padel Academy",
    "Full Address": "Av. João Meireles S/N, Loulé, Quarteira",
    "Latitude": "37.078",
    "Longitude": "-8.118",
    "Phone": "+351 289 324 123",
    "Website": "https://www.tietennis.com/vilamoura",
    "Email": "vta@premier-sports.org",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-9pm\",\"Tuesday\":\"9am-9pm\",\"Wednesday\":\"9am-9pm\",\"Thursday\":\"9am-9pm\",\"Friday\":\"9am-9pm\",\"Saturday\":\"9am-9pm\",\"Sunday\":\"9am-9pm\"}",
    "Additional Information": "Tennis, Padel, Pro shop, Cafe",
    "District": "Faro"
  },
  {
    "Facility Name": "Clube de Ténis de Vila Real de Santo António",
    "Full Address": "8900-211 Vila Real de Sto. António",
    "Latitude": "37.195",
    "Longitude": "-7.417",
    "Phone": "+351 281 541 014",
    "Website": "https://www.facebook.com/groups/3263015170631490",
    "Email": "geral@tenisvrsa.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-12pm, 4pm-8pm\",\"Tuesday\":\"9am-12pm, 4pm-8pm\",\"Wednesday\":\"9am-12pm, 4pm-8pm\",\"Thursday\":\"9am-12pm, 4pm-8pm\",\"Friday\":\"9am-12pm, 4pm-8pm\",\"Saturday\":\"9am-12pm, 4pm-8pm\",\"Sunday\":\"Closed\"}",
    "Additional Information": "Tennis, School",
    "District": "Faro"
  },
  {
    "Facility Name": "Lagos Tenis Center & Pickleball",
    "Full Address": "R. Santa Casa da Misericórdia de Lagos, Torraltinha, 8600-513 Lagos",
    "Latitude": "37.1",
    "Longitude": "-8.67",
    "Phone": "+351 916 175 231",
    "Website": "https://www.facebook.com/profile.php?id=61553888848762",
    "Email": "lagosteniscenter@gmail.com",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"8:30am-6pm\",\"Tuesday\":\"8:30am-6pm\",\"Wednesday\":\"8:30am-6pm\",\"Thursday\":\"8:30am-6pm\",\"Friday\":\"8:30am-6pm\",\"Saturday\":\"8:30am-4pm\",\"Sunday\":\"8:30am-4pm\"}",
    "Additional Information": "Tennis, Training",
    "District": "Faro"
  },
  {
    "Facility Name": "Padel Blu",
    "Full Address": "Rua dos Brejos Nº2, Albufeira, 8200-047",
    "Latitude": "37.09",
    "Longitude": "-8.24",
    "Phone": "+351 911 157 234",
    "Website": "https://www.tietennis.com/PadelBlu",
    "Email": "sports@groupblu.pt",
    "Number of Courts": "Not specified",
    "Operating Hours": "{\"Monday\":\"9am-10pm\",\"Tuesday\":\"9am-10pm\",\"Wednesday\":\"9am-10pm\",\"Thursday\":\"9am-10pm\",\"Friday\":\"9am-10pm\",\"Saturday\":\"9am-8pm\",\"Sunday\":\"9am-8pm\"}",
    "Additional Information": "Padel, Pool, Bar",
    "District": "Faro"
  }
];
